### ISSUE TITLE
Careful: BadMutable [1.0.2]

### ISSUE THREAD

**Issue by CSchnackenberg** [niftylettuce/dayjs-with-plugins#5]
This project is great and worked out of the box.

However, please consider removing [BadMutable](https://day.js.org/docs/en/plugin/bad-mutable) from the list of plugins.

It breaks the immutability of dayjs objects:
```ts
// node.js
const dayjs = require('dayjs-with-plugins') // introduces mutability
//const dayjs = require('dayjs') // uncomment to compare

const now = dayjs();
const tomorrow = now.add(1, 'day');

console.log(now); // << might not be expect
```

I assume BadMutable is just _one of the plugins_ and it's _just there_ but as it changes such a fundamental concept of dayjs that it would be nice to get at least a little hint.

Personally I would vote to drop the plugin.

**Comment by titanism** [comment]
Thanks for letting us know of this.  We've fixed this and added deprecation notice for older versions.

Please upgrade to v1.0.3+ which is now available on npm.

https://github.com/ladjs/dayjs-with-plugins/releases/tag/v1.0.3
